#!/bin/bash

FC=mpif90
CC=mpicc
F90C=mpif90


DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'
OMPFLAG='-openmp'
CFLAGS='-fPIC'
LDADD='-shared-intel'


LIBS="-L${MPI_ROOT}/lib"
INCLUDES="-I${MPI_ROOT}/include"
NOOPTFLAGS='-O0 -fPIC'


FFLAGS="-fPIC -convert big_endian -assume byterecl -align -march=corei7 -axAVX"
#FDEBUG='-W0 -WB'
FFLAGS="$FDEBUG $FFLAGS"


FOPTIM='-O2'

FOPTIM="$FOPTIM -ip -fp-model precise -traceback -ftz"

#DEFINES=$DEFINES' -DNML_TERMINATOR'
FFLAGS="$FFLAGS -mcmodel=large -shared-intel -DNMLTERMINATOR"
