#!/bin/bash
#
# $Header: linux_amd64_ifort+mpi_kenny,v 1.16 2015/06/24 Weifeng Gordon Zhang Exp $
# $Name:  $


FC=mpif90
CC=mpicc
F90C=mpif90

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='/usr/bin/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'
#OMPFLAG='-openmp'
#CFLAGS='-fPIC'
#LDADD='-shared-intel -mcmodel=medium'
LDADD='-shared-intel -mcmodel=large'

LIBS='-L/scylla-b/home/apps/openmpi-1.6.5-intel/lib/ -lmpi -L/share/apps/netcdf-4.1.3_intel-2011.4.191/lib -lnetcdf'
INCLUDES='-I/scylla-b/home/apps/openmpi-1.6.5-intel/include/ -I/share/apps/netcdf-4.1.3_intel-2011.4.191/include'
#LIBS='-L/usr/local/openmpi-1.4.3_intel-2011.4.191/lib -lmpi -L/share/apps/netcdf-4.1.3_intel-2011.4.191/lib -lnetcdf'
#INCLUDES='-I/usr/local/openmpi-1.4.3_intel-2011.4.191/include -I/share/apps/netcdf-4.1.3_intel-2011.4.191/include'
#- used for parallel (MPI) DIVA
#MPIINCLUDEDIR='/nasa/sgi/mpt/2.11r13/include'
#MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'

NOOPTFLAGS='-O1 -fp-model precise'
#NOOPTFLAGS='-O0'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    #FFLAGS="$FFLAGS -fPIC -W0 -WB -convert big_endian -assume byterecl -align"
    FFLAGS="$FFLAGS -W0 -WB -convert big_endian -assume byterecl -align"
    #FOPTIM='-O2 -ipo -fp-model precise -axCORE-AVX-I -xSSE4.2 -traceback -ftz'
    FOPTIM='-O2 -ipo -fp-model precise -xSSE4.2 -traceback -ftz'
    NOOPTFILES='seaice_growth.F calc_oce_mxlayer.F fizhi_lsm.F fizhi_clockstuff.F ini_parms.F'
else
    #  Try to follow IEEE-754
    #FFLAGS="$FFLAGS -fPIC -W0 -WB -convert big_endian -assume byterecl -noalign"
    FFLAGS="$FFLAGS -W0 -WB -convert big_endian -assume byterecl -noalign"
    FOPTIM='-O0'
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

#- For really big executable (> 2 GB), uncomment following 2 lines
#FFLAGS="$FFLAGS -mcmodel=medium -shared-intel"
#CFLAGS="$CFLAGS -mcmodel=medium -shared-intel"
FFLAGS="$FFLAGS -mcmodel=large -shared-intel -DNMLTERMINATOR"
#FFLAGS="$FFLAGS -mcmodel=large -shared-intel"
CFLAGS="$CFLAGS -mcmodel=large -shared-intel"

