#!/bin/bash
#
#  $Header: /MITgcm/tools/build_options/linux_amd64_pgf90+mpi_scylla,v 1.2 2015/05/11 wgz Exp $
#  $Name:  $
#
# tested on scylla.whoi.edu
# pgf90 11.5-0 64-bit target on x86-64 Linux -tp k8-64

#FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X ## _"

FC='mpif90'
CC='mpicc'
LINK='mpif90'

MPI='true'

DEFINES='-DWORDLENGTH=4'
CPP='/usr/bin/cpp -P -traditional'
EXTENDED_SRC_FLAG='-Mextend'

#INCLUDES='-I/usr/mpich/mpich-1.2.6-pgi524/include -I/opt/awi/netcdf-3.6.0-p1/include'
#LIBS='-L/usr/mpich/mpich-1.2.6-pgi524/lib -Mmpi -L/opt/awi/netcdf-3.6.0-p1/lib -lnetcdf'
#INCLUDES='-I/usr/local/openmpi-1.4.3_pgi-11.5-0/include -I/share/apps/netcdf-4.1.3_pgi-11.5-0/include'
#LIBS='-L/usr/local/openmpi-1.4.3_pgi-11.5-0/lib -Dmpi -L/share/apps/netcdf-4.1.3_pgi-11.5-0/lib -lnetcdf'
INCLUDES='-I/scylla-b/home/apps/openmpi-1.6.5-pgi/include/ -I/share/apps/netcdf-4.1.3_pgi-11.5-0/include'
LIBS='-L/scylla-b/home/apps/openmpi-1.6.5-pgi/lib/ -Dmpi -L/share/apps/netcdf-4.1.3_pgi-11.5-0/lib -lnetcdf'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -byteswapio -Mnodclchk"
    FOPTIM='-O2 -Munroll'
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -byteswapio"
    FOPTIM='-tp amd64 -O0 -Munroll -Kieee'
fi
FFLAGS="$FFLAGS -mcmodel=medium"
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8 -mcmodel=medium"
#FFLAGS="$FFLAGS -m64 -Mlarge_arrays -mcmodel=medium"
